version: '3'

services:

  postgres:
    restart: always
    image: postgres:latest
    expose:
      - "5432"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d/
    env_file: .env


  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
